version: '2'
services:
  nginx:
    image: dbrosy/nginx:alpine
    container_name: dbrosy-nginx-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
