FROM nginx:alpine

MAINTAINER Damian Brosnahan

# Copy custom configuration file from the current directory
# COPY ./conf/nginx.conf /etc/nginx/nginx.conf

# add ssl support to container
RUN apk --no-cache add openssl
