version: '2'
services:
  nginx:
    image: dbrosy/nginx
    container_name: dbrosy-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/log/access.log:/var/log/nginx/access.log
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
